### ISSUE TITLE
windows system datetime format cause IIN.dat writing error

### ISSUE THREAD

**Issue by b97209019** [GralDispersionModel/GUI#30]
I am a user in National Taiwan University. The short time format in Taiwan is YYYY/MM/DD.
Every time the GRAL_GUI.exe modifies 'IIN.dat' it pops an error said: Error writing 'IIN.dat'. As I change the system short time format to DD/MM/YYYY, the error message no longer appears and 'IIN.dat' file has some texts. (before changing the short time format, 'IIN.dat' is always empty)

**Comment by MarkusKuntner** [comment]
Dear user, 
many thanks for this bug report. 
We have put a lot of work into the internationalization of the application over the last years, but there is always old code that does not yet meet these requirements. This is why such feedback is so valuable.
I have found the bug and will correct it as soon as possible.
Kind regards
Markus

**Comment by MarkusKuntner** [comment]
@b97209019 : the following date works now, fixed with: 6fe04acc267e4d43c95ffd21ddc2d6ef2290a1dd
This field is hidden by default because this option is not released.
Feel free to test this fix. I need a few more tests before I close the issue.
Kind regards
Markus
![Clipboard01](https://user-images.githubusercontent.com/56679507/77102667-7baec780-6a19-11ea-8bc0-f076cb8f6e00.jpg)

**Comment by MarkusKuntner** [comment]
No further problems found.
