### ISSUE TITLE
no results while trying video #3

### ISSUE THREAD

**Issue by chrisdie** [GralDispersionModel/GUI#69]
Hello everybody,

I like GRAL very much but I can not get it to work with buildings.

I tried video tutorial #3 but the computation is very fast and I do not get any results:

![gral-gui](https://user-images.githubusercontent.com/15226303/92230283-27a27d00-eeab-11ea-871e-89835592777f.JPG)

could you point me to any common mistakes I oversee here? 

thanks a lot!

**Comment by MarkusKuntner** [comment]
Hello chrisdie,
it's hard to answer from a distance without being able to have a look at the project, but I try my best:
- either the buildings are located outside the domain area 
- the buildings heights are 0
- the buildings are smaller than a flow-field grid cell
- my favourite:  the sources are outside the domain area or the source emission rate is 0 (use the "Save" button in the "source groups" section in the source dialog for line sources. This is needed because one line source can be assigned to different source groups)

The GRAL Core Logfile "Logfile_GRALCore.txt" would be helpful in order to isolate the problem.

The latest GRAL version 20.09 checks whether buildings are present in the domain area and displays a warning message if this is not the case. In addition, GUI 20.09 allows you to specify the percentage of a grid cell that must be occupied by a building in order for that cell to be defined as a building (default 60%). GRAL also shows how many cells are blocked by buildings, this information is also improved in the new version 20.09.  
The versions 20.09 are already available on GitHub (also as binaries), and will hopefully be available on the GRAL homepage in the coming weeks. 

Best
Markus
