### ISSUE TITLE
Problem when extracting wind data

### ISSUE THREAD

**Issue by AndresSimonMoral** [GralDispersionModel/GUI#85]
Hello,

I hope you can help me solve this problem.
I am extracting wind data from the *.GFF file, with a Python code following IO_ReadGFF.cs.

When reading my file I find that while nkk, njj, etc are correct, every wind data is zero. It looks like this:
[...] \x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\ [...]

However, wind components do have a value greater than zero when visualizing them on GRAL.

Any idea of what can be causing this?

Thank you very much in advance.
Best,
Andrés.

**Comment by MarkusKuntner** [comment]
Hello Andrés,
if the GRAL cell is below the ground or inside a building, the wind vector is 0. The GUI displays the wind vectors relative to the terrain.
I´ve just checked, that the bottom layer is always 0 (boundary layer to the ground). In fact, not the greatest solution....
And beware: *.gff files are zip containers!
Don't hesitate to ask, if there is no data at higher grid layers above ground.
Best
Markus

**Comment by AndresSimonMoral** [comment]
Hi Markus,

Thank you very much for replying.
I managed to find values greater than 0 on the 11th level, but they don't make sense. This is the piece of code I am using (header is -2), in case I am not doing it correctly:

with zipfile.ZipFile(00001.gff) as myzip:

   with myzip.open('00001.gff', mode='r') as f:
 
    nk       = abs(np.frombuffer(f.read(4),np.dtype('i4'))[0])
    nj        = np.frombuffer(f.read(4),np.dtype('i4'))[0]
    ni        = np.frombuffer(f.read(4),np.dtype('i4'))[0]
    wd       = np.frombuffer(f.read(4),np.dtype('f4'))[0]
    ws       = np.frombuffer(f.read(4),np.dtype('f4'))[0]
    ak        = np.frombuffer(f.read(4),np.dtype('i4'))[0]
    dx        = np.frombuffer(f.read(4),np.dtype('f4'))[0]
    header = np.frombuffer(f.read(4),np.dtype('i4'))[0]                         
 
    u = np.zeros((nk, ni+2, nj+2))
    v = np.zeros((nk, ni+2, nj+2))
    w = np.zeros((nk+1, ni+2, nj+2))
    
    for k in range(nk):
     for i in range(ni):
      linej = f.read((nj+1)*6)
      for j in range(nj):
       u[k,i,j] = np.frombuffer(linej[nj*6:nj*6+2],np.dtype('i2'))[0]*0.01
       v[k,i,j] = np.frombuffer(linej[nj*6+2:nj*6+4],np.dtype('i2'))[0]*0.01
       w[k+1,i,j] = np.frombuffer(linej[nj*6+4:nj*6+6],np.dtype('i2'))[0]*0.01

This is how v looks like in level 14th:
![v_test_z14](https://user-images.githubusercontent.com/89242042/167672237-02f89025-5673-44e7-8ffc-a0bcca0ce250.png)

Thanks again!
Best,
Andrés

**Comment by MarkusKuntner** [comment]
Hello Andrés,
I´ve no experience in Python, but I try a short analysis; and a remark: our code stems from an old fortran basis, using the 1 as 1st index, making things more unreadable

Your code is desinged for the *.gff mode -2, mode -1 (which is the default mode) cannot be read with it. 
In mode -1, however, the loops are simply swapped (i, j and k instead of k, i and j). The difference has an effect when zipping, since within a layer rather equal wind vectors are given and the file thus often becomes smaller when zipping files with mode -2.

range(n) uses the numbers 0 to n-1, but we are writing 1 to n+1 or in Python 0 to n (inclusive)
Using these informations, I would suggest trying the following code for version -2, the buffer is used for performance reasons and is not mandatory:
 
```
for k in range(nk + 1):
 for i in range(ni + 1):
  for j in range(nj + 1):
   u[k,i,j] = np.frombuffer(f.read(2), np.dtype('i2'))[0] * 0.01
   v[k,i,j] = np.frombuffer(f.read(2) ,np.dtype('i2'))[0] * 0.01
   w[k+1,i,j] = np.frombuffer(f.read(2) ,np.dtype('i2'))[0] * 0.01
```
Excuse me for not being able to test this in Python, I hope there is a helpful approach included.
Best
Markus

**Comment by AndresSimonMoral** [comment]
Hello Markus,

Following your advice, the output makes a lot more sense. However, I still get weird results, as if the actual domain was 1/3 of what it should be:
![u_test2_z8](https://user-images.githubusercontent.com/89242042/167870117-219e9f5f-9eb1-4198-a441-ae1877c7d417.png)


Thanks again!
Best,
Andrés.

**Comment by MarkusKuntner** [comment]
Dear Andrés,
sorry, my own code is tricky due to the performance optimizations.  I had to look at the writing routine of the *.gff files to find the problem of my pseudocode above.
The u v and w components are written sequential, so the reading routine (without optimization) should work like this code snippet:
```
for k in range(nk + 1):
    for i in range(ni + 1):
        for j in range(nj + 1):
            u[k,i,j] = np.frombuffer(f.read(2), np.dtype('i2'))[0] * 0.01
        for j in range(nj + 1):
            v[k,i,j] = np.frombuffer(f.read(2), np.dtype('i2'))[0] * 0.01
        for j in range(nj + 1):
            w[k+1,i,j] = np.frombuffer(f.read(2) ,np.dtype('i2'))[0] * 0.01
```
Maybe this hint will help,
Best
Markus

**Comment by AndresSimonMoral** [comment]
Dear Markus,

It finally works! 
The last hint was the key, thank you very much!!

Best,
Andrés.
